---
# AWS Credentials
aws_access_key: "xxxxxxxxxx"
aws_secret_key: "xxxxxxxxxxxxxxxxxxx"
aws_region: "us-east-1"

# VPC Information
vpc_name: "Ali VPC 1"
vpc_cidr_block: "10.0.0.0/16"
tenancy: default #dedicated

# For Security Group Rule
my_ip: "Your public IP address" #Make sure to change it in the security group if your IP address changed

#availability zones
az1: us-east-1a
az2: us-east-1b
az3: us-east-1c

# Subnets Public
public_subnet_1_cidr: "10.0.1.0/24" #Public Application
public_subnet_2_cidr: "10.0.2.0/24" #Public Nat

# Subnets Private
private_subnet_1_cidr: "10.0.3.0/24" #Application Server
private_subnet_2_cidr: "10.0.4.0/24" #Databases Server
private_subnet_3_cidr: "10.0.5.0/24" #Lambda 1
# private_subnet_4_cidr: "10.0.6.0/24" #Lambda 2
# private_subnet_5_cidr: "10.0.7.0/24" #Lambda 3
# private_subnet_6_cidr: "10.0.8.0/24" #Lambda 4


#EndPoint
service_name: "com.amazonaws.{{aws_region}}.s3"

waitTime: 10


# SSH Nat server
nat_ssh_serverImageID: ami-085925f297f89fce1
nat_ssh_serverSize: t2.micro
vpc_ssh_pem_file_name: "ali.pem"